[2025-01-16 16:57:13,747][modelflow.modelflow.__main__][DEBUG] - DEBUG ENABLED
[2025-01-16 16:57:13,747][modelflow.__main__][INFO] - Launch command: ['/home/kuhmichel/anaconda3/envs/eki/bin/modelflow', 'debug=True', 'run=auto', 'scheduler=unix']
[2025-01-16 16:57:13,747][modelflow.__main__][INFO] - Storing run config in global...
[2025-01-16 16:57:13,747][modelflow.__main__][DEBUG] - config:
[2025-01-16 16:57:13,748][modelflow.__main__][DEBUG] - {'debug': True, 'run': {'_target_': 'modelflow.run.Auto', 'tasks': [{'_target_': 'modelflow.run.LayerExchange', 'cmd_args': 'run=train dataset=tsV2 dataset.dataloader.batch_size=2 tokenizer=hf tokenizer.encoding=fhswf/BPE_GPT2_TinyStoriesV2_cleaned_2048 run.epochs=1 tokenizer=hf_gptneo +model.type=CHECKPOINT  model=NEW_BENCH2 quantization=qat quantization/model=NEW_BENCH2b run.export=True', 'source_layer': '', 'targer_layer': ''}]}, 'scheduler': {}, 'runtime': {'choices': {'scheduler': 'unix', 'run': 'auto', 'hydra/env': 'default', 'hydra/callbacks': None, 'hydra/job_logging': 'perlevel', 'hydra/hydra_logging': 'default', 'hydra/hydra_help': 'default', 'hydra/help': 'main', 'hydra/sweeper': 'basic', 'hydra/launcher': 'basic', 'hydra/output': 'default'}}}
[2025-01-16 16:57:13,750][modelflow.__main__][CRITICAL] - Script execution failed. Reason: Error locating target 'modelflow.run.Auto', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: run
Traceback (most recent call last):
  File "/home/kuhmichel/anaconda3/envs/eki/lib/python3.10/site-packages/hydra/_internal/utils.py", line 644, in _locate
    obj = getattr(obj, part)
AttributeError: module 'modelflow' has no attribute 'run'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kuhmichel/anaconda3/envs/eki/lib/python3.10/site-packages/hydra/_internal/utils.py", line 650, in _locate
    obj = import_module(mod)
  File "/home/kuhmichel/anaconda3/envs/eki/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kuhmichel/git/eki-transformer-dev/modelflow/modelflow/run/__init__.py", line 1, in <module>
    from modelflow.run.manuelsequence import ManuelSequence
  File "/home/kuhmichel/git/eki-transformer-dev/modelflow/modelflow/run/manuelsequence.py", line 1, in <module>
    from modelflow.run.common import TaskList
  File "/home/kuhmichel/git/eki-transformer-dev/modelflow/modelflow/run/common.py", line 4, in <module>
    from modelflow.command.common import Command
  File "/home/kuhmichel/git/eki-transformer-dev/modelflow/modelflow/command/__init__.py", line 1, in <module>
    from modelflow.command.sbatch import sattach, sbatch, scancle, squeue
  File "/home/kuhmichel/git/eki-transformer-dev/modelflow/modelflow/command/sbatch.py", line 3, in <module>
    from modelflow.command import common
  File "/home/kuhmichel/git/eki-transformer-dev/modelflow/modelflow/command/common.py", line 7, in <module>
    from modelflow.command.extract import Extractor
  File "/home/kuhmichel/git/eki-transformer-dev/modelflow/modelflow/command/extract.py", line 17, in <module>
    class StdoutStrExtractor(Extractor):
  File "/home/kuhmichel/anaconda3/envs/eki/lib/python3.10/dataclasses.py", line 1184, in dataclass
    return wrap(cls)
  File "/home/kuhmichel/anaconda3/envs/eki/lib/python3.10/dataclasses.py", line 1175, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
  File "/home/kuhmichel/anaconda3/envs/eki/lib/python3.10/dataclasses.py", line 1024, in _process_class
    _init_fn(all_init_fields,
  File "/home/kuhmichel/anaconda3/envs/eki/lib/python3.10/dataclasses.py", line 544, in _init_fn
    raise TypeError(f'non-default argument {f.name!r} '
TypeError: non-default argument 'regex' follows default argument

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kuhmichel/anaconda3/envs/eki/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 134, in _resolve_target
    target = _locate(target)
  File "/home/kuhmichel/anaconda3/envs/eki/lib/python3.10/site-packages/hydra/_internal/utils.py", line 658, in _locate
    raise ImportError(
ImportError: Error loading 'modelflow.run.Auto':
TypeError("non-default argument 'regex' follows default argument")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kuhmichel/git/eki-transformer-dev/modelflow/modelflow/__main__.py", line 57, in main
    app = instantiate(cfg.run)
  File "/home/kuhmichel/anaconda3/envs/eki/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
  File "/home/kuhmichel/anaconda3/envs/eki/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 333, in instantiate_node
    _target_ = _resolve_target(node.get(_Keys.TARGET), full_key)
  File "/home/kuhmichel/anaconda3/envs/eki/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 139, in _resolve_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error locating target 'modelflow.run.Auto', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: run
[2025-01-16 16:57:13,750][modelflow.__main__][ERROR] - Exited with Status Code: 1
