[2025-01-16 15:19:55,464][modelflow.__main__][INFO] - Launch command: ['/home/kuhmichel/anaconda3/envs/eki/bin/modelflow']
[2025-01-16 15:19:55,465][modelflow.__main__][INFO] - Storing run config in global...
[2025-01-16 15:19:55,465][modelflow.__main__][CRITICAL] - Script execution failed. Reason: Key 'run' is not in struct
    full_key: run
    object_type=dict
Traceback (most recent call last):
  File "/home/kuhmichel/git/eki-transformer-dev/modelflow/modelflow/__main__.py", line 58, in main
    run = instantiate(cfg.run)
  File "/home/kuhmichel/anaconda3/envs/eki/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 359, in __getattr__
    self._format_and_raise(key=key, value=None, cause=e)
  File "/home/kuhmichel/anaconda3/envs/eki/lib/python3.10/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/home/kuhmichel/anaconda3/envs/eki/lib/python3.10/site-packages/omegaconf/_utils.py", line 819, in format_and_raise
    _raise(ex, cause)
  File "/home/kuhmichel/anaconda3/envs/eki/lib/python3.10/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/home/kuhmichel/anaconda3/envs/eki/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 351, in __getattr__
    return self._get_impl(
  File "/home/kuhmichel/anaconda3/envs/eki/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 442, in _get_impl
    node = self._get_child(
  File "/home/kuhmichel/anaconda3/envs/eki/lib/python3.10/site-packages/omegaconf/basecontainer.py", line 73, in _get_child
    child = self._get_node(
  File "/home/kuhmichel/anaconda3/envs/eki/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 475, in _get_node
    self._validate_get(key)
  File "/home/kuhmichel/anaconda3/envs/eki/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 164, in _validate_get
    self._format_and_raise(
  File "/home/kuhmichel/anaconda3/envs/eki/lib/python3.10/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/home/kuhmichel/anaconda3/envs/eki/lib/python3.10/site-packages/omegaconf/_utils.py", line 899, in format_and_raise
    _raise(ex, cause)
  File "/home/kuhmichel/anaconda3/envs/eki/lib/python3.10/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
omegaconf.errors.ConfigAttributeError: Key 'run' is not in struct
    full_key: run
    object_type=dict
[2025-01-16 15:19:55,465][modelflow.__main__][ERROR] - Exited with Status Code: 1
